# Generated by Django 2.2.2 on 2019-07-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='commission',
        ),
    ]
